'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4016
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("wow2collada.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;continents&gt;
        '''  &lt;continent name=&quot;azeroth&quot; file=&quot;world\maps\azeroth\azeroth_{0}_{1}.adt&quot;&gt;
        '''    &lt;region name=&quot;redridge&quot; xmin=&quot;35&quot; xmax=&quot;38&quot; ymin=&quot;48&quot; ymax=&quot;50&quot;/&gt;
        '''  &lt;/continent&gt;
        '''  &lt;continent name=&quot;kalimdor&quot; file=&quot;world\maps\kalimdor\kalimdor_{0}_{1}.adt&quot;&gt;
        '''    &lt;region name=&quot;mulgore&quot; xmin=&quot;31&quot; xmax=&quot;34&quot; ymin=&quot;33&quot; ymax=&quot;38&quot;/&gt;
        '''  &lt;/continent&gt;
        '''  &lt;continent name=&quot;outland&quot; file=&quot;world\maps\expansion01\expansion01_{0}_{1}.adt&quot;&gt;
        '''    &lt;region name=&quot;nagrand&quot; xmin=&quot;13&quot; xmax=&quot;21&quot; ymin=&quot;33&quot; ymax=&quot;38&quot;&gt;&lt;/region&gt;
        '''  &lt;/cont [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Regions() As String
            Get
                Return ResourceManager.GetString("Regions", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
